//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ComunicacionRayen.WSCitas {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IMetodosTotemDTS", Namespace="http://tempuri.org/")]
    public partial class MetodosTotemDTS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObtenerCitasPacienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback InformarLlegadaPacienteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MetodosTotemDTS() {
            this.Url = global::ComunicacionRayen.Properties.Settings.Default.ComunicacionRayen_WSCitas_MetodosTotemDTS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObtenerCitasPacienteCompletedEventHandler ObtenerCitasPacienteCompleted;
        
        /// <remarks/>
        public event InformarLlegadaPacienteCompletedEventHandler InformarLlegadaPacienteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ObtenerCitasPaciente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RespuestaObtenerCitasPaciente ObtenerCitasPaciente([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ParametroObtenerCitasPaciente parametroObtenerCitasPaciente) {
            object[] results = this.Invoke("ObtenerCitasPaciente", new object[] {
                        parametroObtenerCitasPaciente});
            return ((RespuestaObtenerCitasPaciente)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCitasPacienteAsync(ParametroObtenerCitasPaciente parametroObtenerCitasPaciente) {
            this.ObtenerCitasPacienteAsync(parametroObtenerCitasPaciente, null);
        }
        
        /// <remarks/>
        public void ObtenerCitasPacienteAsync(ParametroObtenerCitasPaciente parametroObtenerCitasPaciente, object userState) {
            if ((this.ObtenerCitasPacienteOperationCompleted == null)) {
                this.ObtenerCitasPacienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCitasPacienteOperationCompleted);
            }
            this.InvokeAsync("ObtenerCitasPaciente", new object[] {
                        parametroObtenerCitasPaciente}, this.ObtenerCitasPacienteOperationCompleted, userState);
        }
        
        private void OnObtenerCitasPacienteOperationCompleted(object arg) {
            if ((this.ObtenerCitasPacienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCitasPacienteCompleted(this, new ObtenerCitasPacienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("InformarLlegadaPaciente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RespuestaInformarLlegadaPaciente InformarLlegadaPaciente([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ParametroInformarLlegadaPaciente parametroInformarLlegadaPaciente) {
            object[] results = this.Invoke("InformarLlegadaPaciente", new object[] {
                        parametroInformarLlegadaPaciente});
            return ((RespuestaInformarLlegadaPaciente)(results[0]));
        }
        
        /// <remarks/>
        public void InformarLlegadaPacienteAsync(ParametroInformarLlegadaPaciente parametroInformarLlegadaPaciente) {
            this.InformarLlegadaPacienteAsync(parametroInformarLlegadaPaciente, null);
        }
        
        /// <remarks/>
        public void InformarLlegadaPacienteAsync(ParametroInformarLlegadaPaciente parametroInformarLlegadaPaciente, object userState) {
            if ((this.InformarLlegadaPacienteOperationCompleted == null)) {
                this.InformarLlegadaPacienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInformarLlegadaPacienteOperationCompleted);
            }
            this.InvokeAsync("InformarLlegadaPaciente", new object[] {
                        parametroInformarLlegadaPaciente}, this.InformarLlegadaPacienteOperationCompleted, userState);
        }
        
        private void OnInformarLlegadaPacienteOperationCompleted(object arg) {
            if ((this.InformarLlegadaPacienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InformarLlegadaPacienteCompleted(this, new InformarLlegadaPacienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rayensalud.cl.TotemDTS.Entidades")]
    public partial class ParametroObtenerCitasPaciente {
        
        private string runPacienteField;
        
        private ParametroBase parametroBaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RunPaciente {
            get {
                return this.runPacienteField;
            }
            set {
                this.runPacienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ParametroBase ParametroBase {
            get {
                return this.parametroBaseField;
            }
            set {
                this.parametroBaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rayensalud.cl.TotemDTS.Entidades")]
    public partial class ParametroBase {
        
        private string codigoEstablecimientoField;
        
        private string fechaHoraMensajeField;
        
        private string idSitioSoftwareField;
        
        private string idSoftwareInformaField;
        
        private string tipoMensajeField;
        
        private string versionSoftwareInformaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodigoEstablecimiento {
            get {
                return this.codigoEstablecimientoField;
            }
            set {
                this.codigoEstablecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FechaHoraMensaje {
            get {
                return this.fechaHoraMensajeField;
            }
            set {
                this.fechaHoraMensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdSitioSoftware {
            get {
                return this.idSitioSoftwareField;
            }
            set {
                this.idSitioSoftwareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdSoftwareInforma {
            get {
                return this.idSoftwareInformaField;
            }
            set {
                this.idSoftwareInformaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TipoMensaje {
            get {
                return this.tipoMensajeField;
            }
            set {
                this.tipoMensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VersionSoftwareInforma {
            get {
                return this.versionSoftwareInformaField;
            }
            set {
                this.versionSoftwareInformaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rayensalud.cl.TotemDTS.Entidades")]
    public partial class RespuestaInformarLlegadaPaciente {
        
        private RespuestaBase respuestaBaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RespuestaBase RespuestaBase {
            get {
                return this.respuestaBaseField;
            }
            set {
                this.respuestaBaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rayensalud.cl.TotemDTS.Entidades")]
    public partial class RespuestaBase {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descripcionField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rayensalud.cl.TotemDTS.Entidades")]
    public partial class ParametroInformarLlegadaPaciente {
        
        private string idCitaField;
        
        private ParametroBase parametroBaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdCita {
            get {
                return this.idCitaField;
            }
            set {
                this.idCitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ParametroBase ParametroBase {
            get {
                return this.parametroBaseField;
            }
            set {
                this.parametroBaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rayensalud.cl.TotemDTS.Entidades")]
    public partial class Profesional {
        
        private string nombresField;
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string sexoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rayensalud.cl.TotemDTS.Entidades")]
    public partial class Cita {
        
        private string estadoField;
        
        private string fechaField;
        
        private string horaField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private Profesional profesionalField;
        
        private string sectorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Profesional Profesional {
            get {
                return this.profesionalField;
            }
            set {
                this.profesionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Sector {
            get {
                return this.sectorField;
            }
            set {
                this.sectorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rayensalud.cl.TotemDTS.Entidades")]
    public partial class Paciente {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string fechaNacimientoField;
        
        private string nombresField;
        
        private string sexoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rayensalud.cl.TotemDTS.Entidades")]
    public partial class RespuestaObtenerCitasPaciente {
        
        private Paciente pacienteField;
        
        private Cita[] citasField;
        
        private RespuestaBase respuestaBaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Paciente Paciente {
            get {
                return this.pacienteField;
            }
            set {
                this.pacienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Cita[] Citas {
            get {
                return this.citasField;
            }
            set {
                this.citasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RespuestaBase RespuestaBase {
            get {
                return this.respuestaBaseField;
            }
            set {
                this.respuestaBaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ObtenerCitasPacienteCompletedEventHandler(object sender, ObtenerCitasPacienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCitasPacienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCitasPacienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaObtenerCitasPaciente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaObtenerCitasPaciente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void InformarLlegadaPacienteCompletedEventHandler(object sender, InformarLlegadaPacienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InformarLlegadaPacienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InformarLlegadaPacienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaInformarLlegadaPaciente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaInformarLlegadaPaciente)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591